<?php
class I {

// !!! ATTENTION !!! - DO NOT EDIT
// AutoGenerated by ~homebase2/bin/generate-I-class

static function profiler_off        (...$p) : \hbc\profiler\Profiler                             { return i('profiler.off', ...$p); }
static function profiler_on         (...$p) : \hbc\profiler\ProfilerOn                           { return i('profiler.on', ...$p); }
static function report_cli          (...$p) : \hbc\profiler\report\Cli                           { return i('report.cli', ...$p); }
static function report_web          (...$p) : \hbc\profiler\report\Web                           { return i('report.web', ...$p); }
static function log                 (...$p) : \Psr\Log                                           { return i('log', ...$p); }
static function cli                 (...$p) : \hb\Cli                                            { return i('cli', ...$p); }
static function hb_dispatcher       (...$p) : \hb\dispatcher\Dispatcher                          { return i('hb.dispatcher', ...$p); }
static function hb_router           (...$p) : \hb\dispatcher\Router                              { return i('hb.router', ...$p); }
static function hb_processor        (...$p) : \hb\dispatcher\Processor                           { return i('hb.processor', ...$p); }
static function cache               (...$p) : \hbc\cache\adapter\Memcached                       { return i('cache', ...$p); }
static function cache_shm           (...$p) : \hbc\cache\adapter\APC                             { return i('cache/shm', ...$p); }

}
